dist: xenial
language: python
cache: pip
python:
  - "3.5"
  - "3.6"

addons:
  apt:
    packages:
    - ffmpeg

install:
  - pip install mypy pylint
  - pylint --version
  - mypy --version

script:
  - pip install -e .
  - pylint pypopquiz test
  - mypy pypopquiz --ignore-missing-imports
  - python -m unittest discover test
